include:
  - path: compose/dashboard.yaml
    env_file:
      - .env
  - path: compose/management.yaml
    env_file:
      - .env
  - path: compose/media.yaml
    env_file:
      - .env
  - path: compose/sync.yaml
    env_file:
      - .env
  - path: compose/photos.yaml
    env_file:
      - .env
  - path: compose/backup.yaml
    env_file:
      - .env
