- Management:
    - Portainer:
        icon: portainer.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8088
        description: Container management
        server: my-server
        container: portainer

    - File Browser:
        icon: filebrowser.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8089
        description: File management
        server: my-server
        container: file-browser

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8091
        description: Media streaming
        server: my-server
        container: jellyfin

    - Transmission:
        icon: transmission.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8090
        description: BitTorrent client
        server: my-server
        container: transmission-container

    - Calibre Web:
        icon: calibre-web.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8092
        description: eBook library
        server: my-server
        container: calibre-web

- Files & Photos:
    - Syncthing:
        icon: syncthing.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8093
        description: File synchronization
        server: my-server
        container: syncthing

    - Immich:
        icon: immich.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8094
        description: Photo & video backup
        server: my-server
        container: immich_server

- Data:
    - Paperless-ngx:
        icon: paperless-ngx.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8096
        description: Document management
        server: my-server
        container: paperless-ngx

    - Duplicati:
        icon: duplicati.png
        href: http://{{HOMEPAGE_VAR_HOST}}:8095
        description: Encrypted backups
        server: my-server
        container: duplicati
