services:
  duplicati:
    image: lscr.io/linuxserver/duplicati@sha256:9272af8564040fca2959dba7df3f9e1d6f7b08f3a802840e904f309b0b246b16
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ:-Etc/UTC}
      - SETTINGS_ENCRYPTION_KEY=${BACKUP_ENCRYPTION_KEY}
    ports:
      - "8095:8200"
    volumes:
      - ${SSD_DIR}/config/duplicati:/config
      - ${SSD_DIR}:/source/ssd:ro
      - ${HDD_DIR}:/source/hdd:ro
      - ${BACKUP_LOCATION}:/backups
    restart: unless-stopped
