services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx@sha256:4b05bcd28e6923768000b5d247cbf2c66fd49bdc3f3b05955bd4f6790a638b01
    container_name: paperless-ngx
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PAPERLESS_REDIS=redis://paperless-redis:6379
      - PAPERLESS_DBHOST=paperless-db
      - PAPERLESS_DBNAME=${PAPERLESS_DB_NAME:-paperless}
      - PAPERLESS_DBUSER=${PAPERLESS_DB_USERNAME:-paperless}
      - PAPERLESS_DBPASS=${PAPERLESS_DB_PASSWORD:-toChange}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY:-changeme}
      - PAPERLESS_TIME_ZONE=${TZ:-Etc/UTC}
      - PAPERLESS_URL=${PAPERLESS_URL:-http://localhost:8096}
    ports:
      - "8096:8000"
    volumes:
      - ${SSD_DIR}/config/paperless:/usr/src/paperless/data
      - ${HDD_DIR}/documents/media:/usr/src/paperless/media
      - ${HDD_DIR}/documents/consume:/usr/src/paperless/consume
    depends_on:
      - paperless-db
      - paperless-redis
    restart: unless-stopped

  paperless-redis:
    image: redis:7.0.15-alpine@sha256:c9d92d840fd011c908f040592857c724ae6d877f2aba5c40ad963276507386b2
    container_name: paperless-redis
    restart: unless-stopped

  paperless-db:
    image: postgres:15.9-alpine@sha256:3b5f286a417dde5945504ef9156ff9436ffccf428048d7b52c1574c6fc752bb6
    container_name: paperless-db
    environment:
      - POSTGRES_DB=${PAPERLESS_DB_NAME:-paperless}
      - POSTGRES_USER=${PAPERLESS_DB_USERNAME:-paperless}
      - POSTGRES_PASSWORD=${PAPERLESS_DB_PASSWORD:-toChange}
    volumes:
      - ${SSD_DIR}/paperless/postgres:/var/lib/postgresql/data
    restart: unless-stopped
