services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    environment:
      - TZ=${TZ:-Etc/UTC}
    ports:
      - "8088:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SSD_DIR}/config/portainer:/data
    restart: unless-stopped

  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: root
    environment:
      - TZ=${TZ:-Etc/UTC}
    ports:
      - "8089:80"
    volumes:
      - ${SSD_DIR}/config/filebrowser:/config
      - ${SSD_DIR}/config/filebrowser/database:/database
      - ${HDD_DIR}:/srv/hdd
      - ${SSD_DIR}:/srv/ssd
      - ${BACKUP_LOCATION}:/srv/backups
    restart: unless-stopped
