services:
  transmission-container:
    image: linuxserver/transmission@sha256:653e7394633786ef76b3ad7987299dabf730b68646c7fc27826dbb86d20986d4
    container_name: transmission-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Etc/UTC}
    ports:
      - "8090:9091"
      - "51414:51413"
    volumes:
      - ${SSD_DIR}/config/transmission:/etc/transmission-daemon
      - ${HDD_DIR}/media/download:/downloads
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin@sha256:aab0b50a3ce43a41621fc7040a379cc57174059aec8f9c17a90176649a0c1ab1
    container_name: jellyfin
    environment:
      - TZ=${TZ:-Etc/UTC}
    ports:
      - "8091:8096"
      - "8920:8920"
    volumes:
      - ${SSD_DIR}/config/jellyfin:/config
      - ${HDD_DIR}/media:/media
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web@sha256:623a616cbbdf91094ebb6597ef438af56870ef547890282f7112075aff179f59
    container_name: calibre-web
    user: root
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Etc/UTC}
    ports:
      - "8092:8083"
    volumes:
      - ${SSD_DIR}/config/calibre:/config
      - ${HDD_DIR}/media/books:/books
    restart: unless-stopped
