services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./compose/Caddyfile:/etc/caddy/Caddyfile
      - ${SSD_DIR}/config/caddy/data:/data
      - ${SSD_DIR}/config/caddy/config:/config
