services:
  syncthing:
    image: syncthing/syncthing@sha256:4a961394ca471f4e48f31ad2cef50697e502c8799e2e98477a1c3844e0c5bc54
    container_name: syncthing
    hostname: local-syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${HDD_DIR}/sync:/var/syncthing
    ports:
      - 8093:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
