services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: local-syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${BASE_DIR}/backup:/var/syncthing
    ports:
      - 8093:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
